# Generated by Django 3.0.8 on 2020-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Select Country', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default='09092019891'),
            preserve_default=False,
        ),
    ]
